name: CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  NODE_VERSION: "18.19.0"

jobs:
  test-and-build:
    name: Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        env:
          CI: true
        run: |
          npm ci --ignore-scripts
          npm run install:all

      # Code Quality Checks
      - name: Check code formatting
        run: npm run format:check

      - name: Run linting
        run: npm run lint

      - name: Type checking
        run: npm run type-check

      # Security - Basic Only
      - name: Security audit
        run: npm audit --audit-level=high
        continue-on-error: true

      # Tests
      - name: Run tests
        run: npm run test
        continue-on-error: true

      # Build
      - name: Build frontend
        run: npm run build:frontend
        continue-on-error: true
        env:
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET || 'test-secret-for-ci' }}
          NEXTAUTH_URL: http://localhost:3000
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID || 'test-google-id' }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET || 'test-google-secret' }}
          TIKTOK_CLIENT_ID: ${{ secrets.TIKTOK_CLIENT_ID || 'test-tiktok-id' }}
          TIKTOK_CLIENT_SECRET: ${{ secrets.TIKTOK_CLIENT_SECRET || 'test-tiktok-secret' }}

      - name: Build backend
        run: npm run build:backend
        continue-on-error: true

  # Optional: Deploy job (only on main branch)
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test-and-build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Deployment placeholder
        run: |
          echo "🚀 Ready for deployment!"
          echo "Add your deployment steps here when ready"
